apiVersion: v1
kind: Service
metadata:
  name: poi-service
  namespace: api
  labels:
    app: trips
    component: poi
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: trips
    component: poi