apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-namespace-admin
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: Group
    name: 9ad27f30-653a-4584-9ae1-eaa203afaa3b