#This is a SecretProviderClass example using user-assigned identity to access Key Vault
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
  namespace: api
spec:
  provider: azure
  secretObjects:                                 # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - secretName: sql-server-pwd
    type: Opaque
    data: 
    - objectName: SQL-PASSWORD                    # name of the mounted content to sync. this could be the object name or object alias 
      key: pwd
  - secretName: sql-server-user
    type: Opaque
    data: 
    - objectName: SQL-USER                    # name of the mounted content to sync. this could be the object name or object alias 
      key: user
  - secretName: sql-server-server
    type: Opaque
    data: 
    - objectName: SQL-SERVER                    # name of the mounted content to sync. this could be the object name or object alias 
      key: server                       
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "483a1477-c0b2-4fd2-b0a3-38ee23549c72"
    keyvaultName: "k8s-secrets-meo"
    cloudName: ""                   # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: SQL-PASSWORD
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQL-USER
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQL-SERVER
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
    resourceGroup: "teamResources-4"
    subscriptionId: "012f1462-c8ff-4ca5-be75-9a6360ab645d" 
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"                 # the tenant ID of the KeyVault  