kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-policy
  namespace: api
spec:
  podSelector:
    matchLabels:
      app: trips
  ingress:
  - from:
    - namespaceSelector:
        matchLabels: 
          namespace: ingress-basic
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx