apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-namespace-admin
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: Group
    name: 169e9e46-8769-4bd9-8234-f118d272a9e0