apiVersion: v1
kind: Service
metadata:
  name: trip-viewer-service
  namespace: web
  labels:
    app: trips
    component: trip-viewer
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: trips
    component: trip-viewer