apiVersion: v1
kind: Service
metadata:
  name: user-java
  labels:
    app: trips
    component: user-java
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: trips
    component: user-java