apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: api
  labels:
    app: trips
    component: user-java
spec:
  selector:
    matchLabels:
      app: trips
      component: user-java
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: trips
        component: user-java
    spec:
      containers:
      - name: user-java
        image: registryucj0309.azurecr.io/tripinsights/user-java:1.0
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          value: sqladminuCj0309
        - name: SQL_PASSWORD
          value: F4EC5SLm3Bf7
        - name: SQL_SERVER
          value: sqlserverucj0309.database.windows.net